version: '3'

services:
  postgres:
    image: 'postgres:12.1-alpine'
    env_file:
      - '.env'
    ports:
      - 5432:5432
  app:
    depends_on:
      - 'postgres'
    build: .
    network_mode: host
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'

    env_file:
      - '.env'

